module.exports = {
    preset: "ts-jest",
    rootDir: ".",
    roots: ["<rootDir>/src"],
    testMatch: ["**/__tests__/**/*.test.ts", "**/integration/**/*.test.ts"],
    testEnvironment: "node",
    clearMocks: true,
    restoreMocks: true,
    setupFilesAfterEnv: ["<rootDir>/src/test/jest.setup.ts"],
    moduleNameMapper: {
        "^constants/(.*)$": "<rootDir>/src/constants/$1",
        "^domain/(.*)$": "<rootDir>/src/domain/$1",
        "^application/(.*)$": "<rootDir>/src/application/$1",
        "^infrastructure/(.*)$": "<rootDir>/src/infrastructure/$1",
        "^controller/(.*)$": "<rootDir>/src/controller/$1",
        "^routes/(.*)$": "<rootDir>/src/routes/$1",
        "^middleware/(.*)$": "<rootDir>/src/middleware/$1",
        "^config/(.*)$": "<rootDir>/src/config/$1",
        "^test/(.*)$": "<rootDir>/src/test/$1",
        "^app$": "<rootDir>/src/app",
        "^composition-root$": "<rootDir>/src/composition-root",
        "^db$": "<rootDir>/src/db",
    },
    collectCoverageFrom: [
        "src/application/use-cases/**/*.ts",
        "src/domain/entities/**/*.ts",
        "src/domain/errors/**/*.ts",
        "src/middleware/**/*.ts",
        "src/controller/**/*.ts",
        "src/routes/**/*.ts",
        "src/app.ts",
        "!**/__tests__/**",
        "!**/*.types.ts",
    ],
    coverageDirectory: "<rootDir>/coverage",
    coverageProvider: "v8",
    coverageThreshold: {
        global: { branches: 80, functions: 80, lines: 80, statements: 80 },
    },
};
